apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: sample-nginx-rs
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx-rs
    template:
        metadata:
            labels:
                app: nginx-rs
        spec:
            containers:
                - name: nginx
                  image: nginx:1.15
                  ports:
                      - containerPort: 80
